repos:
  - repo: local
    hooks:
      - id: identifier-registry
        name: check identifier registry
        entry: python scripts/check_identifier_registry.py
        language: python
        pass_filenames: false
      - id: validate-scaffold
        name: validate scaffold
        entry: python scripts/validate_scaffold.py
        language: python
        pass_filenames: false
      - id: ensure-tests
        name: ensure tests accompany code changes
        entry: python scripts/check_tests_modified.py
        language: python
        pass_filenames: false
