classdef ReportModelSchemaTest < matlab.unittest.TestCase
    %REPORTMODEL SCHEMA TEST Example structures for ReportModel outputs.
    methods (Test)
        function exampleSchemas(testCase)
            % reportInputs struct example
            reportInputs = struct( ...
                'chunks', table("c1","t1", 'VariableNames', {'chunkId','text'}), ...
                'scores', rand(1,1), ...
                'mdlLDA', struct(), ...
                'vocab', "term1", ...
                'labels', "L1");
            testCase.verifyClass(reportInputs.chunks, "table");

            % reportData struct example
            reportData = struct( ...
                'coverageTable', table(["L1"],[0.5], 'VariableNames',{'label','coverage'}), ...
                'lowConfidence', table("c1", "snippet", 'VariableNames',{'chunkId','text'}), ...
                'ldaTopics', {{"term1","term2"}});
            testCase.verifyClass(reportData.coverageTable, "table");
        end
    end
end
