function tok = init_bert_tokenizer()
%INIT_BERT_TOKENIZER Initialize BERT tokenizer with version compatibility
%
% Returns:
%   tok - bertTokenizer object
%
% This function uses the correct R2025b API where bert() returns both
% the network and tokenizer together.

% R2025b+ syntax: bert() returns [net, tokenizer]
try
    [~, tok] = bert(Model="base");
    return;
catch ME1
    % Fallback: Try without name-value syntax (older MATLAB)
    try
        [~, tok] = bert();
        return;
    catch ME2
        % Provide clear installation instructions based on error type
        if contains(ME1.message, 'Invalid argument') || contains(ME1.message, 'Unrecognized')
            % BERT support package not installed
            error('RegClassifier:BERTModelNotInstalled', ...
                ['BERT model not found. Install ''Text Analytics Toolbox Model for BERT English''.\n\n' ...
                 'Installation steps:\n' ...
                 '  1. In MATLAB Command Window: supportPackageInstaller\n' ...
                 '  2. Select: Text Analytics Toolbox Model for BERT-Base Network\n' ...
                 '  3. Click Install\n\n' ...
                 'Or install via Add-On Explorer: Home > Add-Ons > Get Add-Ons\n' ...
                 'Search for: BERT-Base Network\n\n' ...
                 'Original error: %s'], ...
                ME1.message);
        else
            % Other error
            error('RegClassifier:BERTTokenizerFailed', ...
                ['Failed to initialize BERT tokenizer.\n' ...
                 'BERT is included by default in MATLAB R2025b+.\n' ...
                 'For earlier versions, run: supportPackageInstaller\n\n' ...
                 'Errors:\n' ...
                 '  bert(Model="base"): %s\n' ...
                 '  bert(): %s'], ...
                ME1.message, ME2.message);
        end
    end
end

