function Yweak = weak_rules(textStr, labels)
%WEAK_RULES Keyword-based weak supervision for regulatory topic classification.
%   Yweak = WEAK_RULES(textStr, labels) returns an N-by-K confidence matrix
%   where N = numel(textStr) and K = numel(labels).
%   Labels without a defined rule set produce zero scores.
arguments
    textStr {mustBeText}
    labels {mustBeText}
end

rules = containers.Map;

rules('IRB') = [ ...
    "internal ratings based", "irb approach", "irb permission", ...
    "irb", "slotting", "specialized lending", ...
    "foundation irb", "f-irb", "advanced irb", "a-irb", ...
    "probability of default", "loss given default", "exposure at default", ...
    "pd estimation", "lgd estimation", "ead estimation", ...
    "corporate exposure", "retail exposure", "dilution risk" ...
];

rules('CreditRisk') = [ ...
    "credit risk", "credit conversion factor", "counterparty credit", ...
    "credit quality", "creditworthiness", ...
    "capital requirement for credit", "standardised approach", "sa-cr", ...
    "risk weight", "exposure class", "mitigation techniques", ...
    "credit risk mitigation", "crm", "collateral" ...
];

rules('Securitisation') = [ ...
    "securitisation", "securitization", "tranche", ...
    "originator", "sponsor", ...
    "sts securitisation", "simple transparent standardised", ...
    "senior tranche", "mezzanine tranche", "residual risk", ...
    "synthetic securitisation", "traditional securitisation" ...
];

rules('SRT') = [ ...
    "significant risk transfer", "srt assessment", ...
    "risk retention", ...
    "credit risk transfer", "crt", "risk weight relief", ...
    "first loss", "protection seller" ...
];

rules('MarketRisk_FRTB') = [ ...
    "frtb", "fundamental review", "market risk capital", ...
    "trading book", ...
    "internal model approach", "market risk rwa", "desk-level", ...
    "non-modellable risk factors", "nmrf", ...
    "backtesting", "profit and loss attribution" ...
];

rules('Liquidity_LCR') = [ ...
    "lcr", "liquidity coverage ratio", "liquidity buffer", ...
    "30-day stress", ...
    "high quality liquid assets", "hqla", ...
    "level 1 assets", "level 2a assets", ...
    "net cash outflow", "run-off rate", "inflow cap", ...
    "liquidity coverage requirement" ...
];

rules('Liquidity_NSFR') = [ ...
    "nsfr", "net stable funding ratio", ...
    "stable funding requirement", ...
    "available stable funding", "asf", ...
    "required stable funding", "rsf", ...
    "one-year horizon", "encumbered assets" ...
];

rules('LeverageRatio') = [ ...
    "leverage ratio", "total exposure measure", ...
    "tier 1 capital", ...
    "exposure measure", "off-balance-sheet items", ...
    "derivatives exposure", "securities financing transactions", "sft", ...
    "3% requirement" ...
];

rules('OperationalRisk') = [ ...
    "operational risk", "operational loss", ...
    "business environment", ...
    "advanced measurement approach", ...
    "standardised measurement approach", ...
    "loss event", "business indicator", "internal loss data", ...
    "operational risk capital" ...
];

rules('AML_KYC') = [ ...
    "money laundering", "kyc", "customer due diligence", ...
    "sanctions screening", ...
    "aml", "anti-money laundering", "know your customer", ...
    "cft", "counter financing of terrorism", "sanctions", ...
    "politically exposed person", "pep", ...
    "enhanced due diligence", "edd", "suspicious transaction" ...
];

rules('Governance') = [ ...
    "governance", "board of directors", "management body", ...
    "remuneration policy", ...
    "fit and proper", "suitability assessment", ...
    "internal governance", "risk appetite framework", "raf", ...
    "three lines of defence", "remuneration", ...
    "variable remuneration", "bonus cap" ...
];

rules('Reporting_COREP_FINREP') = [ ...
    "corep", "finrep", "supervisory reporting", ...
    "reporting templates", ...
    "xbrl", "reporting framework", "validation rules", ...
    "corep templates", "finrep templates", ...
    "data quality", "reporting frequency" ...
];

rules('StressTesting') = [ ...
    "stress test", "stress scenario", "adverse scenario", ...
    "macroeconomic stress", ...
    "icaap", "ilaap", "internal capital adequacy", ...
    "internal liquidity adequacy", "scenario analysis", ...
    "reverse stress test", "baseline scenario" ...
];

rules('Outsourcing_ICT_DORA') = [ ...
    "outsourcing", "third-party", "service provider", ...
    "cloud services", ...
    "ict", "information and communication technology", ...
    "dora", "digital operational resilience", ...
    "critical functions", "intra-group outsourcing", ...
    "exit strategy", "concentration risk" ...
];

% Ambiguous short keywords that need a co-occurring context word in the
% same chunk to avoid false positives (e.g. "pd" in non-financial text,
% "sa" in "SALIENT", "lr" in "clearly").
cooccur = containers.Map;
cooccur('pd')  = ["credit","default","obligor","rating","irb","probability","risk"];
cooccur('lgd') = ["credit","default","loss","irb","collateral","recovery"];
cooccur('ead') = ["credit","default","exposure","irb","conversion"];
cooccur('lr')  = ["leverage","capital","tier","exposure","ratio"];
cooccur('sa')  = ["market risk","trading book","frtb","standardised","sensitivity"];
cooccur('ama') = ["operational","loss event","risk capital","measurement"];
cooccur('sma') = ["operational","loss event","risk capital","standardised measurement"];
cooccur('sts') = ["securitisation","securitization","tranche","simple","transparent"];
cooccur('ima') = ["market risk","trading book","frtb","internal model","approval"];
cooccur('srt') = ["risk transfer","securitisation","significant","retention"];
cooccur('asf') = ["stable funding","nsfr","liquidity","available"];
cooccur('rsf') = ["stable funding","nsfr","liquidity","required"];
cooccur('raf') = ["risk appetite","governance","framework","board"];
cooccur('pep') = ["laundering","aml","kyc","politically","due diligence"];
cooccur('edd') = ["due diligence","aml","kyc","enhanced","customer"];
cooccur('sft') = ["securities financing","leverage","repo","margin"];

textStr = lower(string(textStr));
N = numel(textStr);
Yweak = zeros(N, numel(labels));

for j = 1:numel(labels)
    lab = labels(j);
    labKey = char(lab);
    if ~isKey(rules, labKey)
        continue;
    end
    pats = rules(labKey);
    hit = false(N, 1);
    for p = 1:numel(pats)
        kw = char(lower(pats(p)));
        pat = ['\b', regexptranslate('escape', kw), '\b'];
        matched = ~cellfun('isempty', regexp(textStr, pat, 'once'));

        % For ambiguous short keywords, require a context word nearby
        if isKey(cooccur, kw) && any(matched)
            ctxWords = cooccur(kw);
            ctxHit = false(N, 1);
            for c = 1:numel(ctxWords)
                ctxPat = ['\b', regexptranslate('escape', char(ctxWords(c))), '\b'];
                ctxHit = ctxHit | ~cellfun('isempty', regexp(textStr, ctxPat, 'once'));
            end
            matched = matched & ctxHit;
        end

        hit = hit | matched;
    end
    Yweak(:,j) = hit * 0.9;
end
end
