name: Build (Unit & Integration)
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b

      - name: List installed toolboxes
        uses: matlab-actions/run-command@v2
        with:
          command: "ver"

      - name: Hygiene (fixtures, RNG, tags) — HARD
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('tools');
            if ~exist('artifacts/build','dir'), mkdir('artifacts/build'); end
            diary('artifacts/build/hygiene.log');
            try
              tools.check_tests;  % throws on failure -> job fails
            catch ME
              disp(getReport(ME,'extended'));
              diary off;
              rethrow(ME);
            end
            diary off;

      - name: Run tagged tests — HARD
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('tools');
            import matlab.unittest.TestRunner;
            import matlab.unittest.selectors.HasTag;
            import matlab.unittest.TestSuite;
            import matlab.unittest.plugins.XMLPlugin;
            if ~exist('artifacts/build','dir'), mkdir('artifacts/build'); end
            diary('artifacts/build/tests.log');
            try
              s = TestSuite.fromFolder('tests','IncludingSubfolders',true);
              keep = arrayfun(@(t) any(ismember(string(t.Tags), ["unit","synthetic","regression","io-free"])), s);
              s = s(keep);
              r = TestRunner.withTextOutput;
              % JUnit XML output for CI triage
              xmlFile = fullfile('artifacts','build','junit.xml');
              r.addPlugin(XMLPlugin.producingJUnitFormat(xmlFile));
              results = r.run(s);
              assertSuccess(results);
            catch ME
              disp(getReport(ME,'extended'));
              diary off;
              rethrow(ME);
            end
            diary off;

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/build
