name: Clean-room Gate
on:
  pull_request:
    paths:
      - '+reg/**'
      - 'tools/**'
      - 'contexts/**'
      - 'AGENT.md'
      - 'BASE_AGENT.md'
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b

      - name: Print mode (should be clean-room)
        uses: matlab-actions/run-command@v2
        with:
          command: "addpath('tools'); tools.print_mode"

      - name: Run clean-room gate (no tests executed)
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('tools');
            tools.check_style;
            tools.check_contracts;
            tools.check_api_drift;
