name: matlab-lint

on:
  push:
  pull_request:

jobs:
  mlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run mlint
        run: scripts/run_mlint.sh
