name: matlab-lint

on:
  push:
  pull_request:

jobs:
  mlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
      - name: Run mlint
        uses: matlab-actions/run-command@v2
         with:
          command: run_mlint
