name: Optimisation (CC4M + Drift)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '+reg/**'
      - 'reg/**'
      - 'tools/**'
      - 'cc4m_config.json'
      - 'contexts/optimisation.md'
jobs:
  cc4m:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b

      - name: List installed toolboxes
        uses: matlab-actions/run-command@v2
        with:
          command: "ver"

      - name: CC4M Release Gate — HARD
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('tools');
            if ~exist('artifacts/optimisation','dir'), mkdir('artifacts/optimisation'); end
            diary('artifacts/optimisation/gate.log');
            try
              tools.check_style;
              tools.check_contracts;
              tools.check_cc4m;
              tools.check_api_drift;
              fprintf('[gate_cc4m_release] OK\n');
            catch ME
              disp(getReport(ME,'extended'));
              diary off;
              rethrow(ME);
            end
            diary off;

      # Optional perf block (kept soft; uncomment when perf tests exist)
      - name: Performance tests (tag=perf) — SOFT
        uses: matlab-actions/run-command@v2
        continue-on-error: true
        with:
          command: |
            addpath('tools');
            import matlab.unittest.TestRunner;
            import matlab.unittest.TestSuite;
            import matlab.unittest.plugins.XMLPlugin;
            if ~exist('artifacts/optimisation','dir'), mkdir('artifacts/optimisation'); end
            diary('artifacts/optimisation/perf.log');
            try
              s = TestSuite.fromFolder('tests/perf','IncludingSubfolders',true);
              r = TestRunner.withTextOutput;
              xmlFile = fullfile('artifacts','optimisation','perf-junit.xml');
              r.addPlugin(XMLPlugin.producingJUnitFormat(xmlFile));
              results = r.run(s);
              % No assertSuccess: soft, logs only
            catch ME
              disp(getReport(ME,'extended'));
            end
            diary off;

      - name: Upload optimisation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: optimisation-artifacts
          path: artifacts/optimisation
